version: '3'
services:
  flask:
    build: .
    # command: flask run --host=0.0.0.0
    command: gunicorn -w 4 -b 0.0.0.0:5000 webapp:app --reload
    expose:
      - 5000
    volumes:
      - .:/code
    environment: 
      - FLASK_APP=webapp.py
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - flask
